---
- name: Installer Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: Restart Nginx

- name: Déployer la page web depuis un template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: "0644"

- name: Déployer la configuration Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx
